image: docker:latest

variables:
  IMAGENAME: "${REPO}/gitlab"

before_script:
- docker info
- docker login -u ${USERNAME} -p ${PASSWORD} ${REPO}

stages:
- build
- deploy

build:
  stage: build
  only:
   - tags
  script:
  - docker build -t ${IMAGENAME}:${CI_BUILD_TAG} .
  

deploy:
  stage: deploy
  only:
  - tags
  script:
  - docker push ${IMAGENAME}:${CI_BUILD_TAG} 